name: Tests & Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        emacs-version:
          - 27.2
          - 28.2
          - 29.1
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs-version }}
      
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz lcov
      
      - name: Install Cask
        uses: conao3/setup-cask@master
        with:
          version: 'snapshot'
      
      - name: Install project dependencies
        run: cask install
      
      - name: Run tests
        if: matrix.emacs-version != '29.1'
        run: ./run-tests.sh
        
      - name: Run tests with coverage
        if: matrix.emacs-version == '29.1'
        run: make test-coverage
        
      - name: Generate HTML coverage report
        if: matrix.emacs-version == '29.1'
        run: |
          mkdir -p coverage/html
          lcov --summary coverage/lcov.info
          genhtml coverage/lcov.info --output-directory coverage/html
          
      - name: Upload coverage report
        if: matrix.emacs-version == '29.1'
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/html